#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx6144M
kotlin.compiler.execution.strategy=in-process
kotlin.native.jvmArgs=-Xmx12288M
kotlin.mpp.enableCInteropCommonization=true

#Gradle
org.gradle.jvmargs=-Xmx8192M -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1536m
org.gradle.daemon=true
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
